# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: jiri.jkshop::lang.orders.menu_label_single

# Model Form Field configuration
form: $/hambern/properties/models/order/fields.yaml

# Model Class name
modelClass: Hambern\Properties\Models\Order

# Default redirect location
defaultRedirect: hambern/properties/orders

# Create page
create:
    title: jiri.jkshop::lang.orders.create_order
    redirect: hambern/properties/orders/update/:id
    redirectClose: hambern/properties/orders

# Update page
update:
    title: jiri.jkshop::lang.orders.edit_order
    redirect: hambern/properties/orders
    redirectClose: hambern/properties/orders

# Preview page
preview:
    title: jiri.jkshop::lang.orders.preview_order
